identifier_name:
    min_length: # min_length에서
        warning: 2
        error: 1 # 에러만 적용
    max_length: # max_length에서 warning: 40 #40글자 넘으면
        warning: 40
    excluded: # 제외할 문자열 목록 사용
        - id
        - URL

trailing_whitespace:
    ignores_empty_lines: true

line_length:
    warning: 700
    error: 1000
    
function_body_length:
    warning: 500
    error: 700
    
type_body_length:
    warning: 400
    error: 500

excluded:
- Pods

nesting:
  type_level:
    warning: 5
    error: 10
  statement_level:
    warning: 5
    error: 10
    
type_name:
    min_length: 2
